#-----------------------------------------------
#              Virtual Shop Config
#-----------------------------------------------

#DO NOT CHANGE THIS VALUE.
#CHANGING IT COULD RESULT IN DATA LOSS.
ConfigVersion: 1.9

#--------------[General Settings]---------------

general_settings:

  # Users will only be allowed to use the shop in
  # the worlds specified here.
  allowed_worlds:
    - world
    - world_nether
    - world_the_end
  
  # Users will only be allowed to use the shop if
  # they are in the following gamemodes.
  allowed_gamemodes:
    - survival
    - adventure
  
  # The amount of time in milliseconds it takes for
  # a confirmation request to expire. Must be
  # 0 < time, otherwise it will be set to 15 seconds.
  confirmation_timeouts:
    buy: 15000
    ebuy: 15000
    sell: 15000
    esell: 15000
    reprice: 15000
    cancel: 15000
    ecancel: 15000
    
  # Choose whether or not to load VS Reloader.
  # If this is false you cannot use /vs fullreload.
  # Note that if you disable this you will need to
  # manually delete VS Reloader from your plugins folder
  # or it will still be loaded by spigot and be usable.
  enable_vsr: true

#--------------[Database Settings]--------------
# Indicate whether you want to use a MySQL database
# to store plugin data. If you do not use MySQL, a
# SQLite database will be used.

database_settings:

  # True for MySQL, false for SQLite.
  using_MySQL: false
  
  # MySQL Credentials.
  # If using SQLite, this will be ignored.
  MySQL:
    port: 3306
    username: username
    host: localhost
    password: password
    database: minecraft

  # User data is stored based on UUID to prevent data loss
  # through name changes. For database readability, the user's
  # name is also listed, although it is not used at all for
  # identification by the plugin. The names are not upated
  # regularly, therefore if a user changes their name their old
  # name will be listed in the databse. THE UUID WILL REMAIN THE
  # SAME THEREFORE IT WILL NOT IMPACT THE PLUGIN OR ITS DATA.
  #
  # Below you can choose if you want the plugin to sync the names
  # stored in the databases automatically. It is recommended NOT to 
  # turn these on as it can slow down startup/shutdown time as 
  # the databases get filled with more data.
  #
  # Manual syncs can be done ingame via /vs uuidnamesync [uuid]
  UUID_name_syncs:
    # Sync stored names when the server starts.
    on_startup: false
    # Sync stored names when the server shuts down.
    on_shutdown: false

#----------------[Chat Settings]----------------
# Configure the style of the Virtual Shop's messages below.

chat_settings:

  # Broadcast when a user sells an item.
  broadcast_offers: true
  
  details:
    # Prefix that will be prepended to each Virtual Shop message.
    # To add colors to this you must use the format "&<code>".
    # If the header on commands such as /find, stock, sell, vs, or shop
    # is too long after changing this, you may need to adjust the pack
    # sizing below.
    msg_prefix: '&7| &2VShop &7|&e'

    # The name of the server, will be used in several messages.
    server_name: Server

    # Localization for number formating. The two supported values are 'US' and 'EU'.
    # US Format: 1,000.00 | EU Format: 1.000,00 | Symbols are handled by your economy plugin.
    localization: 'US'

    # This is the base color of the Virtual Shop interface. Usually lighter.
    base_color: '&7'

    # This is the trim color of the Virtual Shop interface. Usually darker.
    trim_color: '&2'

    # This will be the color of command help descriptions.
    description_color: '&f'

    # Specify the color of message content.
    message_color: '&e'

    # The color of error messages.
    error_color: '&c'

    # The color of success messages.
    success_color: '&a'
    
    # The color of amounts.
    amount_color: '&6'
    
    # The color of items.
    item_color: '&9'
    
    # The color of prices.
    price_color: '&e'
    
    # The color of buyer names.
    buyer_color: '&b'
    
    # The color of seller names.
    seller_color: '&c'

  #-----------------------------------------------
  # VirtualShop automatically centers some listing 
  # messages to make the UI nicer. This can only be
  # optimized to one resouce pack because the font
  # is different in almost every one. YOU SHOULD ONLY
  # CHANGE THIS IF YOUR SERVER HAS A RESOUCE PACK OTHER
  # THAN DEFAULT or if the header on /find, stock, sell,
  # vs, and shop is not properly centered after modifying
  # the msg_prefix value above.
  #
  # In order to change this, add the pack you're using
  # to the list below using the following syntax:
  #
  # packid:           //The pack id will be used in the selected_pack field.
  #   sizing: number  //Experiment with this until you are satisfied
  #
  # Working examples below.
  # **Note that the sizing is variable to the msg_prefix above. Adjust the value as necessary.
  resoucepacks:
    supported_packs:
      default:
        sizing: 70
      atherys:
        sizing: 78
  
    # Specify a pack id from the supported_packs list.
    selected_pack: default

#----------------[Item Settings]----------------
# Configure item properties such as restrictions.

item_settings:

  #-----------------------------------------------
  #           Item Price Limits
  # Below you can set max price limits for items based on their
  # item id as well as a general max price for all items.
  #  
  # Example below: (// is a comment)
  #
  #     itemid-datavalue:    //If there is no specific data value put 0
  #       name: ItemName     //Not required but helpful for the user
  #       max-price:         //Maximum price the user can sell this item at
  price_limits:
    default_limit: 100000.0
    items:
      399-0: 
        name: NetherStar
        max-price: 1000000.0
      