author: Daniel Scalzi
description: Allows players to buy and sell goods on a VirtualShop.
main: com.dscalzi.virtualshop.VirtualShop
name: VirtualShop
version: 0.152.0
depend: [Vault]
loadbefore: [VSReloader]
commands:
  buy:
    description: Buy goods for sale on the VirtualShop.
    usage: /<command> <amount> <item> [maxprice]
  ebuy:
    description: Browse and purchase enchanted goods on the VirtualShop.
    usage: /<command> <item>
  sell:
    description: Put goods up for sale on the VirtualShop.
    usage: /<command> <amount> <item> <price> | /<command> <amount> <hand/mainhand/offhand> <price>
  esell:
    description: Put enchanted goods up for sale on the VirtualShop.
    usage: /<command> <item> <price>
  cancel:
    description: Removes items from VirtualShop.
    usage: /<command> <item>
  ecancel:
    description: Remove enchanted items from the VirtualShop.
    usage: /<command> <item>
  find:
    description: Find offers for an item.
    usage: /<command> <item>
  stock:
    description: List items for sale.
    usage: /<command> [player] [page]
  sales:
    description: See sales that have been made.
    usage: /<command> [player] [page]
  shop:
    description: Displays help.
    usage: /<command> [page]
  reprice:
    description: Reprices a listing.
    usage: /<command> <item> <price>
  ereprice:
    description: Reprices an enchanted listing.
    usage: /<command> <item> <price>
  vs:
    description: Technical commands under /vs.
    usage: /<command> [param]
permissions:
  virtualshop.*:
    children:
      virtualshop.merchant.*:
        children:
          virtualshop.merchant.lookup: true
          virtualshop.merchant.find: true
          virtualshop.merchant.regular.*:
            children:
              virtualshop.merchant.regular.buy: true
              virtualshop.merchant.regular.cancel: true
              virtualshop.merchant.sell.regular: true
              virtualshop.merchant.reprice.regular: true
          virtualshop.merchant.enchanted.*:
            children:
              virtualshop.merchant.enchanted.buy: true
              virtualshop.merchant.enchanted.cancel: true
              virtualshop.merchant.enchanted.sell: true
              virtualshop.merchant.enchanted.reprice: true
          virtualshop.merchant.sales.*:
            children:
              virtualshop.merchant.sales.individual: true
          virtualshop.merchant.stock.*:
            children:
              virtualshop.merchant.stock.individual: true
      virtualshop.admin.*:
        children:
          virtualshop.admin.formatmarket: true
          virtualshop.admin.reload: true
          virtualshop.admin.reprice.others: true
      virtualshop.developer.fullreload: true