author: Daniel Scalzi
description: Allows players to buy and sell goods on a VirtualShop.
main: com.dscalzi.virtualshop.VirtualShop
name: VirtualShop
version: AvSoft 1.11-R0.1-SNAPSHOT
depend: [Vault]
loadbefore: [VSReloader]
commands:
  buy:
    description: Buy goods for sale on the VirtualShop.
    usage: /<command> <amount> <item> [maxprice]
  sell:
    description: Put goods up for sale on the VirtualShop.
    usage: /<command> <amount> <item> <price> | /<command> <amount> <hand/mainhand/offhand> <price>
  esell:
    description: Put enchanted goods up for sale on the VirtualShop.
    usage: /<command> <item> <price>
  cancel:
    description: Removes items from VirtualShop.
    usage: /<command> <item>
  find:
    description: Find offers for an item.
    usage: /<command> <item>
  efind:
    description: Find offers for an enchanted item.
    usage: /<command> <item>
  stock:
    description: List items for sale.
    usage: /<command> [player] [page]
  sales:
    description: See sales that have been made.
    usage: /<command> [player] [page]
  shop:
    description: Displays help.
    usage: /<command> [page]
  reprice:
    description: Reprices a listing.
    usage: /<command> <item> <price>
  vs:
    description: Technical commands under /vs.
    usage: /<command> [param]
permissions:
  virtualshop.*:
    children:
      virtualshop.merchant.*:
        children:
          virtualshop.merchant.buy: true
          virtualshop.merchant.cancel: true
          virtualshop.merchant.find: true
          virtualshop.merchant.efind: true
          virtualshop.merchant.lookup: true
          virtualshop.merchant.sales.*:
            children:
              virtualshop.merchant.sales: true
              virtualshop.merchant.sales.server: true
          virtualshop.merchant.sell: true
          virtualshop.merchant.esell: true
          virtualshop.merchant.stock.*:
            children:
              virtualshop.merchant.stock: true
              virtualshop.merchant.stock.server: true
          virtualshop.merchant.reprice: true
      virtualshop.admin.*:
        children:
          virtualshop.admin.formatmarket: true
          virtualshop.admin.reloadconfig: true
          virtualshop.admin.uuidnamesync: true
          virtualshop.admin.reprice.others: true
      virtualshop.developer.reload: true