using-MySQL: false
MySQL:
  port: 3306
  username: username
  host: localhost
  password: password
  database: minecraft
broadcast-offers: true
chatty:
  prefix: "&6&l[&f&lA&ftlas&lN&fetwork&6&l] + &f"