#------------------------------------------
#            Virtual Shop Config
#------------------------------------------
using-MySQL: false
MySQL:
  port: 3306
  username: username
  host: localhost
  password: password
  database: minecraft
broadcast-offers: true
chatty:
  prefix: "&5[&dOShop&5]&e"
  server-name: ObsidianCraft
  message-color: "&e"
#------------------------------------------
#           Item Price Limits
#  Below you can set max price limits for 
#  items based on their item id. Example below:
#
#     itemid-datavalue: //if there is no specific data value put 0
#       name: ItemName //not required but helpful for the user
#       max-price: //maximum price the user can sell this item at
#------------------------------------------
price-limits:
  default_limit: 100000
  items:
    399-0: 
      name: NetherStar
      max-price: 1000000
allowed-worlds:
  - Survival
  - Survival_the_end
  - Survival_nether