#-----------------------------------------------
#              Virtual Shop Config
#-----------------------------------------------

#DO NOT CHANGE THIS VALUE.
#CHANGING IT COULD RESULT IN DATA LOSS.
ConfigVersion: 1.9

#--------------[General Settings]---------------

general_settings:

  # Users will only be allowed to use the shop in
  # the worlds specified here.
  allowed_worlds:
    - world
    - world_nether
    - world_the_end

#--------------[Database Settings]--------------
# Indicate whether you want to use a MySQL database
# to store plugin data. If you do not use MySQL, a
# SQLite database will be used.

database_settings:

  #True for MySQL, false for SQLite.
  using_MySQL: false
  
  #MySQL Credentials.
  #If using SQLite, this will be ignored.
  MySQL:
    port: 3306
    username: username
    host: localhost
    password: password
    database: minecraft

#----------------[Chat Settings]----------------
# Configure the style of the Virtual Shop's messages below.

chat_settings:

  #Broadcast when a user sells an item.
  broadcast_offers: true
  
  details:
    #Prefix that will be prepended to each Virtual Shop message.
    #If the header on commands such as /find, stock, sell, vs, or shop
    #is too long after changing this, you may need to adjust the pack
    #sizing below.
    msg_prefix: '&5[&dOShop&5]&e'

    #The name of the server, will be used in several messages.
    server_name: ObsidianCraft

    #Localization for number formating. The two supported values are 'US' and 'EU'.
    #US Format: 1,000.00 | EU Format: 1.000,00 | Symbols are handled by your economy plugin.
    localization: 'US'

    #This is the base color of the Virtual Shop interface. Usually lighter.
    base_color: '&d'

    #This is the trim color of the Virtual Shop interface. Usually darker.
    trim_color: '&5'

    #This will be the color of command help descriptions.
    description_color: '&d'

    #Specify the color of message content.
    message_color: '&e'

    #The color of error messages.
    error_color: '&c'

    #The color of success messages.
    success_color: '&a'

  #-----------------------------------------------
  # VirtualShop automatically centers some listing 
  # messages to make the UI nicer. This can only be
  # optimized to one resouce pack because the font
  # is different in almost every one. YOU SHOULD ONLY
  # CHANGE THIS IF YOUR SERVER HAS A RESOUCE PACK OTHER
  # THAN DEFAULT or if the header on /find, stock, sell,
  # vs, and shop is not properly centered after modifying
  # the msg_prefix value above.
  #
  # In order to change this, add the pack you're using
  # to the list below using the following syntax:
  #
  # packid:           //The pack id will be used in the selected_pack field.
  #   sizing: number  //Experiment with this until you are satisfied
  #
  # Working examples below.
  # **Note that the sizing is variable to the msg_prefix above. Adjust the value as necessary.
  resoucepacks:
    supported_packs:
      default:
        sizing: 70
      atherys:
        sizing: 100
  
    #Specify a pack id from the supported_packs list.
    selected_pack: default

#----------------[Item Settings]----------------
# Configure item properties such as restrictions.

item_settings:

  #-----------------------------------------------
  #           Item Price Limits
  # Below you can set max price limits for items based on their
  # item id as well as a general max price for all items.
  #  
  # Example below: (// is a comment)
  #
  #     itemid-datavalue:    //If there is no specific data value put 0
  #       name: ItemName     //Not required but helpful for the user
  #       max-price:         //Maximum price the user can sell this item at
  price_limits:
    default_limit: 100000
    items:
      399-0: 
        name: NetherStar
        max-price: 1000000
      