author: SwearWord
description: Allows players to buy and sell goods on a VirtualShop.
main: com.dscalzi.virtualshop.VirtualShop
name: VirtualShop
version: OC 1.9.4-R0.2
depend: [Vault]
commands:
    buy:
        description: Buy goods for sale on the VirtualShop.
        usage: /buy <amount> <item> [maxprice]
    sell:
        description: Put goods up for sale on the VirtualShop.
        usage: /sell <amount> <item> <price> | /sell <amount> hand <price>
    cancel:
        description: Removes items from VirtualShop.
        usage: /cancel <item>
    find:
        description: Find offers for an item.
        usage: /price <item>
    stock:
        description: List items for sale.
        usage: /stock [player] [page]
    sales:
        description: See sales that have been made.
        usage: /sales [player] [page]
    shop:
        description: Displays help.
        usage: /shop
    vs:
        description: Technical commands under /vs.
        usage: /vs [param]
permissions:
    virtualshop.access.beta:
        description: Restricts access during beta period
        default: OP
    virtualshop.access.admin:
        description: Access to administrator commands
        default: OP
    virtualshop.sell:
        description: Allow usage of /sell
        default: true
    virtualshop.buy:
        description: Allow usage of /buy
        default: true
    virtualshop.find:
        description: Allow usage of /find
        default: true
    virtualshop.cancel:
        description: Allow usage of /cancel
        default: true
    virtualshop.stock:
        description: Allow usage of /stock
        default: true
    virtualshop.sales:
        description: Allow usage of /sales
        default: true