author: Daniel Scalzi
description: Enables users to buy and sell items on a virtual shop.
main: com.dscalzi.virtualshopx.VirtualShopX
name: VirtualShopX
version: 0.152.0
depend: [Vault]
loadbefore: [VSXReloader]
commands:
  buy:
    description: Buy goods for sale on the virtual shop.
    usage: /<command> <amount> <item> [maxprice]
  ebuy:
    description: Browse and purchase enchanted goods on the virtual shop.
    usage: /<command> <item>
  sell:
    description: Put goods up for sale on the virtual shop.
    usage: /<command> <amount> <item> <price> | /<command> <amount> <hand/mainhand/offhand> <price>
  esell:
    description: Put enchanted goods up for sale on the virtual shop.
    usage: /<command> <item> <price>
  cancel:
    description: Removes items from virtual shop.
    usage: /<command> <item>
  ecancel:
    description: Remove enchanted items from the virtual shop.
    usage: /<command> <item>
  find:
    description: Find offers for an item.
    usage: /<command> <item>
  stock:
    description: List items for sale.
    usage: /<command> [player] [page]
  sales:
    description: See sales that have been made.
    usage: /<command> [player] [page]
  shop:
    description: Displays help.
    usage: /<command> [page]
  reprice:
    description: Reprices a listing.
    usage: /<command> <item> <price>
  ereprice:
    description: Reprices an enchanted listing.
    usage: /<command> <item> <price>
  vs:
    description: Technical commands under /vs.
    usage: /<command> [param]
permissions:
  virtualshopx.*:
    children:
      virtualshopx.merchant.*:
        children:
          virtualshopx.merchant.lookup: true
          virtualshopx.merchant.regular.*:
            children:
              virtualshopx.merchant.regular.buy: true
              virtualshopx.merchant.regular.sell: true
              virtualshopx.merchant.regular.cancel: true
              virtualshopx.merchant.regular.reprice: true
              virtualshopx.merchant.regular.find: true
          virtualshopx.merchant.enchanted.*:
            children:
              virtualshopx.merchant.enchanted.buy: true
              virtualshopx.merchant.enchanted.sell: true
              virtualshopx.merchant.enchanted.cancel: true
              virtualshopx.merchant.enchanted.reprice: true
          virtualshopx.merchant.sales.*:
            children:
              virtualshopx.merchant.sales.individual: true
          virtualshopx.merchant.stock.*:
            children:
              virtualshopx.merchant.stock.individual: true
      virtualshopx.admin.*:
        children:
          virtualshopx.admin.formatmarket: true
          virtualshopx.admin.reload: true
      virtualshopx.developer.*:
        children:
          virtualshopx.developer.fullreload: true